// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8T-Yhubt83clFsS8rc225HkAquuT-xRI',
    appId: '1:214423697250:web:4ac08f2cad8d52a33d5e3b',
    messagingSenderId: '214423697250',
    projectId: 'communityapp-hakumai22',
    authDomain: 'communityapp-hakumai22.firebaseapp.com',
    databaseURL: 'https://communityapp-hakumai22-default-rtdb.firebaseio.com',
    storageBucket: 'communityapp-hakumai22.firebasestorage.app',
    measurementId: 'G-0E0Y14DNMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSg86UcouYRGJ9mR_eOy-Hc90NtMN-Vc',
    appId: '1:214423697250:android:a760dc37742009f83d5e3b',
    messagingSenderId: '214423697250',
    projectId: 'communityapp-hakumai22',
    databaseURL: 'https://communityapp-hakumai22-default-rtdb.firebaseio.com',
    storageBucket: 'communityapp-hakumai22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3mW01gGwn3yoVWY_SEJy51Es21h9O85A',
    appId: '1:214423697250:ios:d0879650533dce863d5e3b',
    messagingSenderId: '214423697250',
    projectId: 'communityapp-hakumai22',
    databaseURL: 'https://communityapp-hakumai22-default-rtdb.firebaseio.com',
    storageBucket: 'communityapp-hakumai22.firebasestorage.app',
    iosBundleId: 'hakumai22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3mW01gGwn3yoVWY_SEJy51Es21h9O85A',
    appId: '1:214423697250:ios:156361ebe5b273f83d5e3b',
    messagingSenderId: '214423697250',
    projectId: 'communityapp-hakumai22',
    databaseURL: 'https://communityapp-hakumai22-default-rtdb.firebaseio.com',
    storageBucket: 'communityapp-hakumai22.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8T-Yhubt83clFsS8rc225HkAquuT-xRI',
    appId: '1:214423697250:web:58cda678a0a7e2123d5e3b',
    messagingSenderId: '214423697250',
    projectId: 'communityapp-hakumai22',
    authDomain: 'communityapp-hakumai22.firebaseapp.com',
    storageBucket: 'communityapp-hakumai22.firebasestorage.app',
    measurementId: 'G-14H3ZP5LX7',
  );
}
